### ISSUE TITLE
Constant parameters in new_fris_coefficients.py

### ISSUE THREAD

**Issue by tmcclintock** [ehannah/FrisbeeResearch#1]
The parameters in this file need to be inputs to the functions, since they will be tested later.

For instance, in the coef_L(alpha) function, both param_L_0 and param_L_alpha are both constants (defined above). They need to be able to be changed somehow. To do so you would need something like:

def coef_L(alpha, param_L_0, param_L_alpha):
...

**Comment by ehannah** [comment]
Ok, I think I fixed it in this section. I saw your comment on the unit vectors code. If I made the correct changes here, I'll go back and do it there too.
