### ISSUE TITLE
Consant unit vectors in angle_of_attack.py

### ISSUE THREAD

**Issue by tmcclintock** [ehannah/FrisbeeResearch#2]
This issue is similar to the one for the new_fris_coefficients.py. In the angle_of_attack.py file the unit vectors are being created from the rotation matrix in a static environment, i.e. not in a function.

This means that the unit vectors are calculated **once** when the file is imported somewhere else (i.e. when someone writes "import angle_of_attack"). This is not what we want. We want the unit vectors recalculated any time the rotation matrix is recalculated.

**Comment by ehannah** [comment]
So should it instead look more like this?: 

`def xbhat(phi, theta):`
`return np.rm.rotationmatrix(phi,theta).transpose()[0]`
